#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Bebop1/pose
        child_frame_id: Bebop1/base_link
        parent_frame_id: world
    '2':
        pose: Bebop2/pose
        child_frame_id: Bebop2/base_link
        parent_frame_id: world
    '3':
        pose: Bebop3/pose
        child_frame_id: Bebop3/base_link
        parent_frame_id: world
    '4':
        pose: Bebop4/pose
        child_frame_id: Bebop4/base_link
        parent_frame_id: world
    '11':
        pose: Target1/pose
        child_frame_id: Target1/base_link
        parent_frame_id: world
    '12':
        pose: Target2/pose
        child_frame_id: Target2/base_link
        parent_frame_id: world
#optitrack_config:
 #       multicast_address: 224.0.0.1
